### ISSUE TITLE
画面のアスペクト比を自動で合わせる

### ISSUE THREAD

**Issue by muraki111** [Massa2201/react-native_demo#1]
- 特定のスマホで画面の上下に白い余白ができるので，自動で画面サイズにフィットさせる
![image](https://github.com/Massa2201/react-native_demo/assets/60808536/efa1ea04-9f3a-4740-b324-beea08a69cca)

**Comment by muraki111** [comment]
App.jsに記載されている★の箇所を0に変更することで解決する
```javascript
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",

    paddingVertical: 50, ★
  },
});
```

**Comment by Massa2201** [comment]
paddingVertical: 50,を消す流れがあったのでクローズ

**Comment by muraki111** [comment]
消したコミットと，消した理由を書いておくと後々なんだっけ？ってのが起きないと思う
- [コミット](https://github.com/Massa2201/react-native_demo/commit/92288a18c5ade1476bd30d42f63987b9fece9534)
